<a>Action</a>
        <a>Adventure</a>
        <a>Anime</a>
        <a>Comedy</a>
        <a>Comic</a>
        <a>Documentary</a>
        <a>Drama</a>
        <a>Fantasy</a>
        <a>Horror</a>
        <a>Kids</a>
        <a>Romance</a>
        <a>Sci-fi</a>
        <a>Teen</a>
        <a>War</a>   